#include <iostream>
#include "Viewer.h"

using namespace std;

int main( int argc, char** argv )
{
	if( argc != 6 )
	{
		cerr << "usage: " << argv[0] << " density x_grid y_grid z_grid density_field.txt " << endl;
		return 1;
	}

	// Need to read in the density field from the file format (directly to the Spatial Hash)

	// Need to Spatial Hash the density field?
	// Need to interpolate density field to the vertices of the voxel grid for marching cubes

	Viewer viewer;
	for( int arg = 5; arg < argc; ++arg ){
		viewer.fields.addField( argv[arg] );
	}
	viewer.init();

	// 



	// Need to visualize the density field points
	// Need to visualize the voxel_grid points
	// Need to visualize the triangles generated by Marching Cubes

	return 0;
}

